FriendsServise/urls.py
import sys
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('service.urls'))
]

service/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "service"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path('logout', views.logout_request, name='logout'),

    path('find_user', views.find_user, name='find_user'),
    path('outgoing', views.outgoing_friend_request_list, name='outgoing'),

    path('send_friend_request', views.send_friend_request, name='send_friend_request'),
    path('cancel_friend_request', views.cancel_friend_request, name='cancel_friend_request'),

]

service/models.py
from django.contrib.auth.models import User
from django.db import models


class OutgoingRequests(models.Model):
    from_user_id = models.IntegerField(blank=False)
    to_user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING)


class IngoingRequests(models.Model):
    to_user_id = models.IntegerField(blank=False)
    from_user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING)

service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserFindForm(forms.Form):
    username = forms.CharField(required=True)

service/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from .forms import NewUserForm, UserFindForm
from .models import OutgoingRequests, IngoingRequests


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("service:homepage")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="service/register.html", context={"register_form": form})


def homepage(request):
    # return HttpResponse('<h1>Hello</h1>')
    return render(request=request, template_name="service/home.html")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # print(type(user.id))
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("service:homepage")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="service/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("service:homepage")


def find_user(request):
    if request.method == "POST":
        user = request.user
        form = UserFindForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            finded_user = User.objects.filter(username=username).first()
            if finded_user is not None:
                status = 0
                f1 = False
                f2 = False
                # print(OutgoingRequests.objects.get(to_user_id=finded_user, from_user_id=user.id))
                try:
                    outgoing = OutgoingRequests.objects.get(to_user_id=finded_user, from_user_id=user.id)
                except OutgoingRequests.DoesNotExist:
                    outgoing=None

                try:
                    ingoing = IngoingRequests.objects.get(from_user_id=finded_user, to_user_id=user.id)
                except IngoingRequests.DoesNotExist:
                    ingoing=None

                if outgoing is not None:
                    f1 = True
                if ingoing is not None:
                    f2 = True

                if not f1 and not f2:
                    status = 1
                if f1 and not f2:
                    status = 2
                if not f1 and f2:
                    status = 3
                if f1 and f2:
                    status = 4

                return render(request=request, template_name="service/find_user.html",
                              context={"find_form": form, "status": status, "username": username})
            else:
                return render(request=request, template_name='service/Error404.html')

    form = UserFindForm()
    return render(request=request, template_name="service/find_user.html", context={"find_form": form, })


def outgoing_friend_request_list(request):
    user = request.user
    outgoing =set(map(lambda x: x.to_user_id.username, OutgoingRequests.objects.filter(from_user_id=user.id).all()))
    ingoing = set(map(lambda x: x.from_user_id.username, IngoingRequests.objects.filter(to_user_id=user.id).all()))



    friends = set.intersection(outgoing, ingoing)
    outgoing_result = outgoing.difference(ingoing)
    ingoing_result = ingoing.difference(outgoing)

    return render(request=request, template_name="service/outgoing.html", context={"outgoing": outgoing_result, "ingoing": ingoing_result, "friends": friends})


def send_friend_request(request):
    username = request.GET.get('username', None)
    print(username)
    user = request.user

    finded_user = User.objects.filter(username=username).first()
    OutgoingRequests.objects.create(from_user_id=user.id, to_user_id=finded_user)
    IngoingRequests.objects.create(to_user_id=finded_user.id, from_user_id=user)

    return redirect("service:find_user")


def cancel_friend_request(request):
    username = request.GET.get('username', None)
    print(username)
    user = request.user

    finded_user = User.objects.filter(username=username).first()
    OutgoingRequests.objects.get(from_user_id=user.id, to_user_id=finded_user).delete()
    IngoingRequests.objects.get(to_user_id=finded_user.id, from_user_id=user).delete()

    return redirect("service:find_user")

FriendsServise/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {%block title%}
    <title>Title</title>
    {% endblock %}
</head>
<body>

<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  {% if user.is_authenticated %}
  <a class="navbar-brand" href="{% url 'service:homepage' %}">Welcome, {{user.username}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'service:find_user' %}">Check the status of friendship</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'service:outgoing' %}">Get user stats</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'service:logout' %}">Logout</a>
      </li>
    </ul>
  </div>

  {% else %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'service:login' %}">Login</a>
      </li>
    </ul>
  </div>

  {% endif %}
</nav>

{% block content %}

{% endblock %}

</body>
</html>

FriendsServise/templates/service/Error404.html
{% extends "base.html" %}

{% block content %}

<h1>Page not found. Error 404</h1>

{% endblock %}

FriendsServise/templates/service/find_user.html
{% extends "base.html" %}

{% block content %}      

{% load crispy_forms_tags %}


<div class="container py-5">
  <h1>Find User by Username</h1>
  <form method="POST">
    {% csrf_token %}
    {{ find_form|crispy }}
    <button class="btn btn-primary" type="submit">Find</button>
  </form>

  {% if status == 1 %}
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5">
    <h1 class="text-body-emphasis">Упс.... Вы пока не дружите с этим пользователем</h1>
    <p class="col-lg-6 mx-auto mb-4">
      Никогда не поздно это исправить. Смелее
    </p>
    <button class="btn btn-primary px-5 mb-5" type="submit" onclick="location.href='{% url 'service:send_friend_request' %}?username={{username}}'">
      Отправить заявку в друзья
    </button>
  </div>
  {% elif status == 2 %}
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5">
    <h1 class="text-body-emphasis">Вашу заявку пока не приняли</h1>
    <p class="col-lg-6 mx-auto mb-4">
      Никогда не поздно обидеться на это. Поторопите вашего друга или удалите заявку
    </p>
    <button class="btn btn-primary px-5 mb-5" type="submit" onclick="location.href='{% url 'service:cancel_friend_request' %}?username={{username}}'">
      Отменить заявку
    </button>
  </div>
  {% elif status == 3 %}
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5">
    <h1 class="text-body-emphasis">Пользователь отправил вам заявку в друзья</h1>
    <p class="col-lg-6 mx-auto mb-4">
      Ну нельзя же быть таким бездушным. Скорее прими заявку. Не обижай человека
    </p>
    <button class="btn btn-primary px-5 mb-5" type="submit" onclick="location.href='{% url 'service:send_friend_request' %}?username={{username}}'">
      Принять заявку
    </button>
  </div>
  {% elif status == 4 %}
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5">
    <h1 class="text-body-emphasis">Пользователь у вас в друзьях</h1>
    <p class="col-lg-6 mx-auto mb-4">
      Вы дружите дружную дружбу. Но что если друг тебе надоел, или того хуже - как либо подставил или предал? Как минимум после этого стоит удалить его из друзей
    </p>
    <button class="btn btn-primary px-5 mb-5" type="submit" onclick="location.href='{% url 'service:cancel_friend_request' %}?username={{username}}'">
      Удалить из друзей
    </button>
  </div>
  {% endif %}

</div>

{% endblock %}

FriendsServise/templates/service/home.html
{% extends "base.html" %}

FriendsServise/templates/service/login.html
{% extends "base.html" %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'service:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

FriendsServise/templates/service/logout.html
{% extends "base.html" %}

{% block content %}
<button class="btn btn-primary" type="submit">Logout</button>

{% endblock %}

FriendsServise/templates/service/outgoing.html
{% extends "base.html" %}

{% block content %}

<div class="d-flex">

    <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary" style="width: 380px;">
        <a href="#"
           class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom">
            <span class="fs-5 fw-semibold">Исходящие заявки</span>
        </a>
        <div class="list-group list-group-flush border-bottom scrollarea">
            {% for item in outgoing %}
            <a href="#" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
                <div class="d-flex w-100 align-items-center justify-content-between">
                    <strong class="mb-1">{{item}}</strong>
                </div>
                <div class="col-10 mb-1 small">Ваша заявка еще не принята</div>
            </a>
            {% endfor %}

        </div>
    </div>

    <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary" style="width: 380px;">
        <a href="#"
           class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom">
            <span class="fs-5 fw-semibold">Входящие заявки</span>
        </a>
        <div class="list-group list-group-flush border-bottom scrollarea">
            {% for item in ingoing %}
            <a href="#" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
                <div class="d-flex w-100 align-items-center justify-content-between">
                    <strong class="mb-1">{{item}}</strong>
                </div>
                <div class="col-10 mb-1 small">У вас новая заявка</div>
            </a>
            {% endfor %}

        </div>
    </div>
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary" style="width: 380px;">
        <a href="#"
           class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none border-bottom">
            <span class="fs-5 fw-semibold">Друзья</span>
        </a>
        <div class="list-group list-group-flush border-bottom scrollarea">
            {% for item in friends %}
            <a href="#" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
                <div class="d-flex w-100 align-items-center justify-content-between">
                    <strong class="mb-1">{{item}}</strong>
                </div>
                <div class="col-10 mb-1 small">Вы дружите с {{item}}</div>
            </a>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

FriendsServise/templates/service/register.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'service:login' %}">login</a> instead.</p>
</div>

{% endblock %}